spring:
  datasource:
    name: jdbc/mysql
    driver-class-name: com.mysql.jdbc.Driver
    username: user1   #数据库账号
    password: 123456  #数据库密码
    url: jdbc:mysql://localhost:3306/homework?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC #demo为数据库名称
    type: javax.sql.DataSource
  resources:
    static-locations: classpath:/templates/
jpa:
  show-sql: true
hibernate:
  ddl-auto: update
devtools:
  restart:
    enabled: true
jackson:
  date-format: yyyy-MM-dd
time-zone: GMT+8

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8888
